name: reactive-resume-start

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgbouncer:
    image: edoburu/pgbouncer:latest
    restart: unless-stopped
    environment:
      POOL_MODE: transaction
      AUTH_TYPE: scram-sha-256
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.68
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "9100:9000" # S3 API
      - "9101:9001" # Admin UI
    environment:
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_ACCESS_KEY=rustfs
      - RUSTFS_SECRET_KEY=rustfs
    volumes:
      - rustfs_data:/data
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "curl -f http://localhost:9000/health && curl -f http://localhost:9001/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  gotenberg:
    image: gotenberg/gotenberg:edge
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CHROMIUM_AUTO_START=true
      - LIBREOFFICE_DISABLE_ROUTES=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - TZ=UTC
  #     - NODE_ENV=production
  #     # App
  #     - APP_URL=http://localhost:3000
  #     - PRINTER_APP_URL=http://app:3000
  #     # Printer
  #     - GOTENBERG_ENDPOINT=http://gotenberg:3000
  #     # Database
  #     - DATABASE_URL=postgresql://postgres:postgres@pgbouncer:5432/postgres
  #     # Auth
  #     - AUTH_SECRET=this-is-a-super-secret-key
  #     # Storage
  #     - S3_ACCESS_KEY_ID=rustfs
  #     - S3_SECRET_ACCESS_KEY=rustfs
  #     - S3_ENDPOINT=http://localhost:9100
  #     - S3_BUCKET=reactive-resume-start
  #   volumes:
  #     - ./data:/app/data
  #   depends_on:
  #     pgbouncer:
  #       condition: service_healthy
  #   healthcheck:
  #     test:
  #       [
  #         "CMD",
  #         "bun",
  #         "-e",
  #         "fetch('http://localhost:3000/api/health').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))",
  #       ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

volumes:
  rustfs_data:
  postgres_data:
  chromium_data:
